# Generated by Django 4.2.2 on 2023-07-01 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name', 'author', '-time_create', '-is_publish'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['deadline', 'course', 'module', 'is_publish'], 'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='homeworkanswer',
            options={'ordering': ['-time_create', 'user', 'homework', 'status'], 'verbose_name': 'Ответ на домашнее задание', 'verbose_name_plural': 'Ответы на домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='messagecourse',
            options={'ordering': ['-time_create', 'user', '-is_publish'], 'verbose_name': 'Сообщение курса', 'verbose_name_plural': 'Сообщения курсов'},
        ),
        migrations.AlterModelOptions(
            name='messagemodule',
            options={'ordering': ['-time_create', 'user', '-is_publish'], 'verbose_name': 'Сообщение модуля', 'verbose_name_plural': 'Сообщения модулей'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name', 'course', '-time_create', 'is_publish'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='status',
            field=models.CharField(choices=[('ns', 'не сдано'), ('s', 'сдано'), ('rat', 'оценено')], default='не сдано', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='messagemodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.module', verbose_name='Модуль'),
        ),
    ]
